/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:4c150a8e-8ed3-4e5a-ae87-3bbc7a9cc78e",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_fDMhUw0gL",
    "aws_user_pools_web_client_id": "4hm5edkfasns8sdf3ccfu7tmda",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://cc3jvsmwszarnd54jn64tzlfi4.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
